MyMvcWebApp10pm/Controllers/PDFTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HiQPdf;
namespace MyMvcWebApp10pm.Controllers
{
    public class PDFTestController : Controller
    {
        // GET: PDFTest
      
 
            public ActionResult Index()
            {
                ViewBag.Message = "Welcome to ASP.NET MVC!";
                Session["MySessionVariable"] = "My Session Variable Value assigned in Index";
                return View();
            }

            public ActionResult About()
            {
                return View();
            }

            public string RenderViewAsString(string viewName, object model)
            {
                // create a string writer to receive the HTML code
                StringWriter stringWriter = new StringWriter();

                // get the view to render
                ViewEngineResult viewResult = ViewEngines.Engines.FindView(ControllerContext, viewName, null);
                // create a context to render a view based on a model
                ViewContext viewContext = new ViewContext(
                        ControllerContext,
                        viewResult.View,
                        new ViewDataDictionary(model),
                        new TempDataDictionary(),
                        stringWriter
                        );

                // render the view to a HTML code
                viewResult.View.Render(viewContext, stringWriter);

                // return the HTML code
                return stringWriter.ToString();
            }

            [HttpPost]
            public ActionResult ConvertThisPageToPdf()
            {
                // get the HTML code of this view
                string htmlToConvert = RenderViewAsString("Index", null);

                // the base URL to resolve relative images and css
                String thisPageUrl = this.ControllerContext.HttpContext.Request.Url.AbsoluteUri;
                String baseUrl = thisPageUrl.Substring(0, thisPageUrl.Length - "PDFTest/ConvertThisPageToPdf".Length);

                // instantiate the HiQPdf HTML to PDF converter
                HtmlToPdf htmlToPdfConverter = new HtmlToPdf();

                // hide the button in the created PDF
                htmlToPdfConverter.HiddenHtmlElements = new string[] { "#convertThisPageButtonDiv" };

                // render the HTML code as PDF in memory
                byte[] pdfBuffer = htmlToPdfConverter.ConvertHtmlToMemory(htmlToConvert, baseUrl);

                // send the PDF file to browser
                FileResult fileResult = new FileContentResult(pdfBuffer, "application/pdf");
                fileResult.FileDownloadName = "ThisMvcViewToPdf.pdf";

                return fileResult;
            }

            [HttpPost]
            public ActionResult ConvertAboutPageToPdf()
            {
                // get the About view HTML code
                string htmlToConvert = RenderViewAsString("About", null);

                // the base URL to resolve relative images and css
                String thisPageUrl = this.ControllerContext.HttpContext.Request.Url.AbsoluteUri;
                String baseUrl = thisPageUrl.Substring(0, thisPageUrl.Length - "PDFTest/ConvertAboutPageToPdf".Length);

                // instantiate the HiQPdf HTML to PDF converter
                HtmlToPdf htmlToPdfConverter = new HtmlToPdf();

                // render the HTML code as PDF in memory
                byte[] pdfBuffer = htmlToPdfConverter.ConvertHtmlToMemory(htmlToConvert, baseUrl);

                // send the PDF file to browser
                FileResult fileResult = new FileContentResult(pdfBuffer, "application/pdf");
                fileResult.FileDownloadName = "AboutMvcViewToPdf.pdf";

                return fileResult;
            }
        }
    }

MyMvcWebApp10pm/Views/PDFTest/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h2>@ViewBag.Message</h2>
<p>
    To learn more about ASP.NET MVC visit ASP.NET MVC Website
</p>
<br />
@using (Html.BeginForm("ConvertThisPageToPdf", "PDFTest", FormMethod.Post, new { id = "convertForm" }))
{
    <div id="convertThisPageButtonDiv">
        <input type="submit" value="Convert
                        This Page To PDF" />
    </div>
}
<br />
@using (Html.BeginForm("ConvertAboutPageToPdf", "PDFTest", FormMethod.Post, new { id = "convertForm" }))
{
    <div id="convertAboutPageButtonDiv">
        <input type="submit" value="Convert
                        About Page To PDF" />
    </div>
}
<br />
<br />
<h1>
    @Session["MySessionVariable"].ToString()
</h1>
<br />
<br />
<img alt=""
     style="height: 100px"
     src="/Images/banner.png" />


Source Code Example - Index View MVC Code

<%@@ Page Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
    Home Page
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h2>
        <%: (String)ViewBag.Message %>
    </h2>
    <p>
        To learn more about ASP.NET MVC visit ASP.NET MVC Website
    </p>
    <br />
    <form action="/PDFTest/ConvertThisPageToPdf" id="convertThisPageForm" method="post">
        <div id="convertThisPageButtonDiv">
            <input type="submit" value="Convert
                        This Page To PDF" />
        </div>
    </form>
    <br />
    <form action="/PDFTest/ConvertAboutPageToPdf" id="convertAboutPageForm"
          method="post">
        <div id="convertAboutPageButtonDiv">
            <input type="submit" value="Convert
                        About Page To PDF" />
        </div>
    </form>
    <br />
    <br />
   
    <br />
    <br />